jodconverter:
  local:

    enabled: true
    office-home: C:\Program Files (x86)\OpenOffice 4
    port-numbers: 2002
    kill-existing-process: true
    process-timeout: 250000
    process-retry-interval: 1000
    max-tasks-per-process: 20
    task-execution-timeout: 250000
    task-queue-timeout: 90000
    #working-dir: /tmp
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages
